/* Generated By:JavaCC: Do not edit this line. AssignmentConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AssignmentConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int DEF = 1;
  /** RegularExpression Id. */
  int MAIN = 2;
  /** RegularExpression Id. */
  int LBRACE = 3;
  /** RegularExpression Id. */
  int RBRACE = 4;
  /** RegularExpression Id. */
  int LBRACK = 5;
  /** RegularExpression Id. */
  int RBRACK = 6;
  /** RegularExpression Id. */
  int SCOLON = 7;
  /** RegularExpression Id. */
  int SPACE = 8;
  /** RegularExpression Id. */
  int NEWLINE = 9;
  /** RegularExpression Id. */
  int PLUS = 10;
  /** RegularExpression Id. */
  int MUL = 11;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 12;
  /** RegularExpression Id. */
  int FUNCTION_NAME = 13;
  /** RegularExpression Id. */
  int PARAMETER_NAME = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"DEF\"",
    "\"MAIN\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\" \"",
    "\"\\n\"",
    "\"+\"",
    "\"*\"",
    "<INTEGER_LITERAL>",
    "<FUNCTION_NAME>",
    "<PARAMETER_NAME>",
  };

}
